version: '3.3'

services:
  web_app:
    build: .
    image: sephix/mps:latest
    container_name: mps-web-app
    restart: on-failure
    ports:
      - "3000:3000"

  nginx:
    image: sephix/nginx:latest
    container_name: mps-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web_app
